{% set name = "pyiron-data" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyiron/pyiron-resources/archive/{{ version }}.tar.gz
  sha256: d71b2e9743963a1932483edab41b818d1d8683a2bcda86c7ca2d9357a4451606

build:
  noarch: generic
  number: 0

requirements:
  build:
  run:
    - sphinxdft-data >=0.0.1
    - iprpy-data >=2021.2.23

test:
  commands:
    - test -f ${PREFIX}/share/pyiron/atomistics/periodic_table.csv  # [unix]
    - test -f ${PREFIX}/share/pyiron/atomicrex/bin/run_atomicrex_1.0.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/thermodynamics/bin/run_sxharmpottst_0.1.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/thermodynamics/bin/run_sxdynmat_0.1.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/thermodynamics/bin/run_sxuniqdispl_0.1.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/sphinx/potentials/potentials_sphinx.csv  # [unix]
    - test -f ${PREFIX}/share/pyiron/sphinx/potentials/potentials_sphinx_jth_default.csv  # [unix]
    - test -f ${PREFIX}/share/pyiron/sphinx/bin/run_sphinx_2.6.1.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/sphinx/bin/run_sphinx_2.6.1_mpi.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/interactive/bin/run_sxextoptinteractive_0.0.1.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/lammps/bin/run_lammps_2020.03.03.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/lammps/bin/run_lammps_2020.03.03_mpi.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/lammps/bin/run_lammps_2018.03.16.bat  # [unix]
    - test -f ${PREFIX}/share/pyiron/mlip/bin/run_lammpsmlip_2020.12.24.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/mlip/bin/run_lammpsmlip_2020.12.24_mpi.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/mlip/bin/run_mlip_1.0.0.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/mlip/bin/run_mlip_1.0.0_mpi.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/mlip/bin/run_mlipjob_1.0.0.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/mlip/bin/run_mlipjob_1.0.0_mpi.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/mlip/bin/run_mlipselect_1.0.0.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/runner/bin/run_runner_1.2.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/pacemaker/bin/run_pacemakerjob_0.0.1.5.sh  # [unix]
    - test -f ${PREFIX}/share/pyiron/runner/bin/run_runner_1.2_mpi.sh  # [unix]

about:
  home: https://pyiron.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pyiron - an integrated development environment (IDE) for computational materials science.
  description: |
    pyiron was initially developed in the Computational Materials Design department of Joerg Neugebauer at the
    Max Planck Insitut für Eisenforschung (Max Planck Insitute for iron research) as a framework for ab initio
    thermodynamics. In collaboration with the Interdisciplinary Centre for Advanced Materials Simulation (ICAMS)
    the framework was recently extended for high throughput applications resulting in the opensource release of
    pyiron.
  doc_url: https://pyiron.readthedocs.io
  dev_url: https://github.com/pyiron

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - muh-hassani
    - niklassiemer
